# The Problem
<!-- 
Outlining the issue / weak point / problem to be solved by this proposal. This should be a compelling section that sets the reader up for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Have there been previous attempts to resolve the problem
 - [ ] Why it should be tackled
-->


R is widely used in the pharmaceutical industry, but rarely within the context of regulatory submissions.  A submission requires the company to collate all relevant statistical analyses and other supporting evidence to support their claims about their new drug or medical device.  This includes the code required to reproduce the analysis.  Filing for submission is an extremely significant milestone for any company and such Quality Assurance (QA) teams tend to take a risk averse approach to the submission.  In the context of statistical code, the QA teams need to be extremely confident that the code is behaving as intended.  As a result, the question of software validity is often raised when discussing the option of generating submission code through R.  

According to the FDA’s [Glossary of Computer System Software Development Terminology](https://www.fda.gov/iceci/inspections/inspectionguides/ucm074875.htm):

>*"**Validation:** Establishing documented evidence which provides a high degree of assurance that a specific process consistently produces a product meeting its predetermined specifications and quality attributes."*

The R Foundation have released [R: Regulatory Compliance and Validation Issues. A Guidance Document for the Use of R in Regulated Clinical Trial Environments](https://www.r-project.org/doc/R-FDA.pdf) which describes the issue of validation and the R Foundation's interpretation of the regulations with respect to base R and the recommend packages.  However, a typical R installation includes hundreds of R packages beyond the base distribution and for the overwhelming majority of packages on CRAN, no such documentation exists to describe the authors' development practices.

To use R as part of a qualified, validated environment, for submission analyses, the industry as whole needs a mechanism for assessing package accuracy and consistency and evaluated the associated risk.  Rather than simply developing and maintaining a large suite of tests the R Validation Hub community feels that a risk-based approach to the adoption of R packages can be widely adopted across the industry.  This risk-based approach evaluates both best practice in package development and the extent of exposure / testing within the R community.  Much of the approach is described over sections of the [R Validation Hub website](https://www.pharmar.org/), although an upcoming white paper (due for release in October 2019) will provide a more concise summary of the group's thinking on the subject.

The aim of this project is to standardise and simplify the risk assessment of R packages, reducing the burden of package evaluation/testing that would otherwise fall on internal R programming experts.  In the absence of any such risk-assessment mechanism for the majority of the R Validation Hub members, it is envisaged that tool adoption will be widespread and the impact felt immediately.


