# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->
This project is a key component in phase II of the R Validation Hub's overall roadmap.  The project itself breaks down into two distinct components:

1. Build upon the riskmetric R package
2. Construct a risk assessment app

The package is already available with MIT + file LICENSE and a prototype of the app was shared with colleagues from across industry at the R/Pharma conference in August 2019.  The start-up phase is therefore affectively complete already although if funding is secured then a contractor needs to be found to assist in the implementation of both the package and app.

The aim is to complete both pieces by the end of July 2020 and share these with the rest of the industry at the 2020 R/Pharma Conference.

## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->
### The riskmetric R package

The package itself is already in very good shape technically and instructions on how to extend the package and generate additional metricsare described [here](https://pharmar.github.io/riskmetric/articles/extending-riskmetric.html).  The development of riskmetric therefore simply requires the addition of remaining metrics.  

A list of metrics has already been identified.  The metrics will therefore be grouped together by the collection mechanism (eg scraping CRAN vs RStudio download logs vs ...) and worked on in batches.

### The Risk Assessment App

A database will firts be created to store: 

* The metrics generated by riskmetric
* Assessor comments, made by those using the app

In parallel, work can begin on creating the front end, which will render the collected metrics for any package that the user chooses.  Once work on the database is complete, the front end can be hooked up such that user comments are written back to the database.  This will allow users to restart the app and continue their assessments.

A reporting mechanism that makes use of Rmarkdown has already been tested in a prototype app.  The prototype app generates HTML reports.  This will be re-used for the main app.  Once the app is functionally running, work will begin to allow users to export to other formats such as PDF and RTF.

## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->
The content of the app was discussed in detail during phase I of the roadmap and very little additional planning is expected to be required.  The group uses slack as its main comms channel with monthly group meetings and executive committee meetings in place to check on progress and outstanding actions.

